name: Say hello

on:
  push:
    branches:
      - main
# EVERY time its send the commit to the branch main execute this workflow push.
# the yml
jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola midu!"
      - name: Dime la fecha
        run: date
      - run: ls -l